# Generated by Django 4.1.3 on 2023-02-15 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskapp', '0010_alter_avalanche_grid_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='avalanche_axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('avalanche_axis', models.CharField(max_length=255)),
                ('avalanche_axis_code', models.CharField(max_length=5)),
                ('aor', models.CharField(max_length=255)),
                ('grids', models.CharField(max_length=1000)),
                ('axis_code_afg', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
