# Generated by Django 4.1.3 on 2023-02-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0013_avalanche_axis_temp_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='avalanche_axis_temporary_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('grid_id', models.CharField(max_length=1000)),
                ('no_of_axis', models.IntegerField()),
                ('avalanche_axis', models.JSONField()),
                ('avalanche_code', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='avalanche_axis_temp_data',
        ),
    ]
