# Generated by Django 4.1.3 on 2023-02-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0014_avalanche_axis_temporary_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_axis_temporary_data',
            name='avalanche_axis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avalanche_axis_temporary_data',
            name='avalanche_code',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
