# Generated by Django 4.1.3 on 2023-02-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0015_alter_avalanche_axis_temporary_data_avalanche_axis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_grid',
            name='grid_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
