# Generated by Django 4.1.3 on 2023-02-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0016_alter_avalanche_grid_grid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_axis',
            name='avalanche_axis_code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='avalanche_axis',
            name='axis_code_afg',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
