# Generated by Django 4.1.3 on 2023-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0017_alter_avalanche_axis_avalanche_axis_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avalanche_axis_temporary_data',
            name='outlook',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
