# Generated by Django 4.1.3 on 2023-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0018_avalanche_axis_temporary_data_outlook'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_grids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('sect_id', models.FloatField()),
                ('forecast_area', models.CharField(max_length=50)),
                ('natsat_grids', models.CharField(max_length=1500)),
            ],
        ),
    ]
