# Generated by Django 4.1.3 on 2023-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0019_weather_grids'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=50)),
                ('relation_in_char', models.CharField(max_length=255)),
                ('intensity', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('Legend', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='weather_grids',
            old_name='created_on',
            new_name='added_on',
        ),
    ]
