# Generated by Django 4.1.3 on 2023-03-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0021_delete_weather_codes_delete_weather_grids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avalanche_axis',
            name='created_by',
        ),
    ]
