# Generated by Django 4.1.3 on 2023-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0022_remove_avalanche_axis_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_axis',
            name='grids',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
