# Generated by Django 4.1.3 on 2023-02-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_user_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointers',
            name='point_type',
            field=models.CharField(choices=[('marker', 'marker'), ('label', 'label')], max_length=255),
        ),
    ]
