# Generated by Django 4.1.3 on 2023-03-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_pointers_point_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointers',
            name='point_type',
            field=models.CharField(choices=[('marker', 'marker'), ('label', 'label'), ('station', 'station')], max_length=255),
        ),
    ]
