# Generated by Django 4.1.3 on 2022-11-23 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_user_date_joined_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('99e9308e-061a-466d-bf53-0dc5b5f56e4f')),
        ),
    ]
