# Generated by Django 4.1.3 on 2022-11-23 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appointment_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0fe606b0-de63-4f30-add2-10881d2eed74'), unique=True),
        ),
    ]
