# Generated by Django 4.1.3 on 2022-11-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_appointment_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='uid',
        ),
    ]
