# Generated by Django 4.1.3 on 2022-11-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_user_id_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
    ]
