# Generated by Django 4.1.2 on 2022-11-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_appointment_image_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
