# Generated by Django 4.1.2 on 2022-11-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_appointment_image_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='send_security',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Director', 'Director'), ('Associate Director', 'Associate Director'), ('Tech Director', 'Tech Director'), ('GH/DH ', 'GH/DH'), ('Employee', 'Employee'), ('Security officer', 'Security officer')], max_length=40),
        ),
    ]
