# Generated by Django 4.1.2 on 2022-11-29 00:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_appointment_send_security_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('8fa8bf06-aac4-4667-ac8e-8e68c3072650')),
        ),
    ]
