# Generated by Django 4.1.2 on 2022-11-29 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('07b1fbe3-961c-450b-b942-8369417af625')),
        ),
    ]
