# Generated by Django 4.1.3 on 2022-11-28 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('4d701e2d-2d1e-45b3-9c2e-465cb1aa95ea')),
        ),
    ]
