# Generated by Django 4.1.2 on 2022-11-30 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_clearance_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('5758d081-4bb0-49d1-9c8b-144a6151bd9d')),
        ),
    ]
