# Generated by Django 4.1.2 on 2022-11-30 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('2a044c82-7af6-4b80-80eb-3698db8a75df')),
        ),
    ]
