# Generated by Django 4.1.2 on 2022-11-30 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('9440167e-5171-425b-93ff-e69d5214d9e7')),
        ),
    ]
