# Generated by Django 4.1.2 on 2022-12-01 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('bcf2f657-3ada-42d8-92ca-46e505f7cfa6')),
        ),
    ]
