# Generated by Django 4.1.2 on 2022-12-02 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_appointment_tem_id_forgetmessagerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reason_cancelation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('c781be18-254f-42ef-82e9-bab664f65e70')),
        ),
    ]
