# Generated by Django 4.1.2 on 2022-12-04 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('7af9d7c5-1b0b-4b53-a086-ad574d80b904')),
        ),
    ]
