# Generated by Django 4.1.2 on 2022-12-07 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('318f876d-4de0-4cf1-b094-9cbd80212aea')),
        ),
    ]
