# Generated by Django 4.1.2 on 2022-12-07 18:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('0d8feb6b-dc1b-4da5-8363-5a2fb801f20e')),
        ),
    ]
