# Generated by Django 4.1.2 on 2022-12-07 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_appointment_tem_id_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('ec59b5cb-11c1-41e6-828c-b971221e0628')),
        ),
    ]
