# Generated by Django 4.1.2 on 2022-12-07 23:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_appointment_tem_id_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgetmessagerequest',
            old_name='user_id',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='employee_id',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('d8cfd583-c445-436d-8184-295830dbdd30')),
        ),
    ]
