# Generated by Django 4.1.2 on 2022-12-07 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_user_id_forgetmessagerequest_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('7d4a47a1-5f13-4d45-bea5-8b7028f478ac')),
        ),
    ]
