# Generated by Django 4.1.7 on 2023-02-23 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='items',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='adhaar_no',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pis',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('721c187d-d9d3-48e3-a136-ac6359b8463b')),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Director', 'Director'), ('Associate Director', 'Associate Director'), ('Tech Director', 'Tech Director'), ('GH/DH', 'GH/DH'), ('Employee', 'Employee'), ('Security officer', 'Security officer')], max_length=40),
        ),
    ]
