# Generated by Django 4.1.7 on 2023-02-23 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_appointment_duration_appointment_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('d56e15e2-4f70-48b9-bf7d-1fe976e7646a')),
        ),
    ]
