# Generated by Django 4.1.7 on 2023-02-24 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_appointment_clearance_level_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accommodation_requirement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('d48c0fae-ca6f-4b89-923e-501acc2e4b35')),
        ),
    ]
