# Generated by Django 4.1.7 on 2023-02-24 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_appointment_accommodation_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('630d4934-c6d5-4ce5-ae34-c4ba409874d7')),
        ),
        migrations.AlterField(
            model_name='user',
            name='pis',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
