# Generated by Django 4.1.7 on 2023-02-24 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_appointment_tem_id_alter_user_pis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('aac81ff5-ea7e-4d8d-884c-02a884e9396c')),
        ),
    ]
