# Generated by Django 4.1.7 on 2023-02-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clearance_level',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('yellow', 'yellow'), ('brown', 'brown')], max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('f6a06740-db3b-4199-85e0-0aab1cd3633e')),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Director', 'Director'), ('Associate Director', 'Associate Director'), ('Tech Director', 'Tech Director'), ('GH/DH', 'GH/DH'), ('Employee', 'Employee'), ('Security officer', 'Security officer'), ('ld', 'ld')], max_length=40),
        ),
        migrations.CreateModel(
            name='pvt_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('c_id_card_no', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pvtemployee')),
                ('items', models.TextField()),
                ('level_of_clearance', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('yellow', 'yellow'), ('brown', 'brown')], max_length=200)),
                ('visit_date', models.DateField(auto_now=True)),
                ('duration', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('drdo_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
