# Generated by Django 4.1.7 on 2023-02-24 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_appointment_clearance_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('bcf8f1ac-f902-421c-9f14-0bb068f70732')),
        ),
    ]
