# Generated by Django 4.1.7 on 2023-02-27 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_appointment_tem_id_delete_pvt_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('1e36450d-c0e5-4aa8-9e9a-4654084733a7')),
        ),
    ]
