# Generated by Django 4.1.7 on 2023-02-27 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_appointment_ld_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='department',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('52125279-879f-4b08-95fd-460d3b2ac94a')),
        ),
    ]
