# Generated by Django 4.1.7 on 2023-02-27 06:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_appointment_final_clearance_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('329e5916-a785-44e6-9106-1ba6003d455e')),
        ),
    ]
