# Generated by Django 4.1.7 on 2023-02-27 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_user_so_ld_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('6d38c257-8baa-4f17-bac2-74a8826ed8c0')),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Director', 'Director'), ('Associate Director', 'Associate Director'), ('Tech Director', 'Tech Director'), ('GH/DH', 'GH/DH'), ('Employee', 'Employee'), ('Security officer', 'Security officer'), ('oic', 'oic')], max_length=40),
        ),
    ]
