# Generated by Django 4.1.7 on 2023-02-27 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_appointment_tem_id_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('2bd5062f-5930-4fad-9d95-d253a076a268')),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Director', 'Director'), ('Associate Director', 'Associate Director'), ('Tech Director', 'Tech Director'), ('GH/DH', 'GH/DH'), ('Employee', 'Employee'), ('Security officer', 'Security officer'), ('oic', 'oic'), ('hwmg', 'hwmg')], max_length=40),
        ),
    ]
