# Generated by Django 4.1.7 on 2023-02-28 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_alter_appointment_tem_id_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='send_oic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('4d5c2bd8-28a9-4521-a77c-58170851ab67')),
        ),
    ]
