# Generated by Django 4.1.7 on 2023-03-01 05:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_appointment_tem_id_alter_user_so_ld'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='perm_id',
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('22785dcb-1b10-4deb-b7df-f088a34189a0')),
        ),
    ]
