# Generated by Django 4.1.7 on 2023-03-01 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_appointment_perm_id_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('58e13472-1342-4b7d-a8e5-638c7e7c0022')),
        ),
    ]
