# Generated by Django 4.1.7 on 2023-03-01 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_alter_appointment_perm_id_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('6bee0706-b05d-4d8b-82fa-219458c60a8f')),
        ),
    ]
