# Generated by Django 4.1.7 on 2023-03-01 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_appointment_age_appointment_height_appointment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('44cbd0ab-4b61-4a42-b981-55140e47c4dd')),
        ),
    ]
