# Generated by Django 4.1.7 on 2023-03-01 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('dfb17d7c-7486-4b8b-ab32-b0078c9ea782')),
        ),
    ]
