# Generated by Django 4.1.7 on 2023-03-02 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_appointment_posted_by_appointment_pvt_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_file', models.FileField(upload_to='download_files')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('f505e606-867c-4b67-a33b-79c0e7e031ad')),
        ),
    ]
