# Generated by Django 4.1.7 on 2023-03-02 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_downloadfile_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('abeb5f8a-9412-448d-afc0-7fd469a58fcc')),
        ),
    ]
