# Generated by Django 4.1.7 on 2023-03-02 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('c1bf2443-54f1-4dc2-bc0e-59f05999cc62')),
        ),
    ]
