# Generated by Django 4.1.7 on 2023-03-03 04:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('df2049f4-54c6-4103-8eea-5c99c9888a0e')),
        ),
    ]
