# Generated by Django 4.1.7 on 2023-03-03 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('53b4838f-c019-4a68-8316-49c13a16c5a9')),
        ),
    ]
