# Generated by Django 4.1.7 on 2023-03-03 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_appointment_close_clearance_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='close_clearance_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('7816556e-86cb-427c-b986-a8f574e21f7e')),
        ),
    ]
