# Generated by Django 4.1.7 on 2023-03-03 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0070_appointment_close_clearance_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('a66269c8-d245-4e71-8947-bfc75b3a80eb')),
        ),
    ]
