# Generated by Django 4.1.7 on 2023-03-03 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('87d852c6-984c-4818-8978-2bd07fe193a9')),
        ),
    ]
