# Generated by Django 4.1.7 on 2023-03-03 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('e366ef94-d13f-4c79-a56b-fd5a9c030a93')),
        ),
    ]
