# Generated by Django 4.1.7 on 2023-03-06 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='transporation_requirement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('3036b304-46cf-48d6-bcc3-950645ca9181')),
        ),
    ]
