# Generated by Django 4.1.7 on 2023-03-07 04:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_appointment_visited_alter_appointment_tem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='visited',
        ),
        migrations.AddField(
            model_name='appointment',
            name='visited_staus',
            field=models.CharField(choices=[('visited', 'visited'), ('not visited', 'not visited'), ('pending', 'pending')], default='pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tem_id',
            field=models.UUIDField(default=uuid.UUID('c202721f-2ad5-45d1-a0e1-a30ffbc32bf7')),
        ),
    ]
