# Generated by Django 4.1.3 on 2023-02-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0043_avalanche_message_two_ack_avalanche_message_two_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='axis_ids',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='avalanche_message_one',
            name='forecast_codes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
