# Generated by Django 4.1.3 on 2023-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0044_alter_avalanche_message_one_axis_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='observatory_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.IntegerField(default=80)),
                ('state_code', models.IntegerField(verbose_name=range(1, 9))),
                ('station_code', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_temperature', models.IntegerField()),
                ('min_temperature', models.IntegerField()),
                ('dry_bulb_temperature', models.IntegerField()),
                ('wet_bulb_temperature', models.IntegerField()),
                ('atmospheric_pressure', models.IntegerField()),
                ('initial_anemometer_reading', models.CharField(max_length=255)),
                ('wind_direction', models.CharField(max_length=255)),
                ('speed_kmph', models.CharField(max_length=25)),
                ('average_wind_speed', models.CharField(max_length=25)),
                ('rh', models.CharField(max_length=25)),
                ('cloud_amount', models.CharField(max_length=8)),
                ('cloud_type', models.CharField(max_length=2)),
                ('present_weather', models.CharField(max_length=2)),
                ('fresh_snow_amount', models.CharField(max_length=3)),
                ('fresh_snow_duration', models.CharField(max_length=4)),
                ('fresh_snow_density', models.CharField(max_length=3)),
                ('crystal_type_code', models.CharField(max_length=2)),
                ('fresh_snow_water_equivalent', models.CharField(max_length=3)),
                ('rainfall', models.CharField(max_length=4)),
                ('total_snow_amount', models.CharField(max_length=3)),
                ('total_snow_water_equivalent', models.CharField(max_length=3)),
                ('standing_snow', models.CharField(max_length=4)),
                ('snow_surface_temperature', models.CharField(max_length=3)),
                ('snow_characteristic_code', models.CharField(max_length=2)),
                ('snow_appearance_code', models.CharField(max_length=1)),
                ('free_penetration', models.CharField(max_length=2)),
                ('crust_thickness', models.CharField(max_length=2)),
                ('penetration_below_crust', models.CharField(max_length=2)),
                ('sunshine', models.CharField(max_length=4)),
                ('avalanche_feedback', models.CharField(max_length=1)),
                ('avalanche_warning', models.CharField(max_length=1)),
            ],
        ),
    ]
