# Generated by Django 4.1.3 on 2023-02-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0046_observatory_data_json_packet_observatory_data_packet'),
    ]

    operations = [
        migrations.CreateModel(
            name='snow_strom_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('packet', models.CharField(max_length=255)),
                ('json_packet', models.JSONField()),
                ('message_type', models.IntegerField(default=81)),
                ('state_code', models.IntegerField(verbose_name=range(1, 9))),
                ('station_code', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date', models.CharField(max_length=6)),
                ('time_commencement', models.TimeField()),
                ('strom', models.CharField(max_length=1)),
                ('strom_number', models.IntegerField()),
                ('time_of_observation', models.CharField(max_length=4)),
                ('strom_status', models.CharField(max_length=1)),
                ('present_weather', models.CharField(max_length=2)),
                ('cloud_amount', models.CharField(max_length=1)),
                ('cloud_type', models.CharField(max_length=2)),
                ('rainfall', models.CharField(max_length=4)),
                ('anemometer_reading', models.CharField(max_length=6)),
                ('average_wind_speed', models.CharField(max_length=3)),
                ('wind_direction', models.CharField(max_length=2)),
                ('dry_bulb_temperature', models.CharField(max_length=3)),
                ('wet_bulb_temperature', models.CharField(max_length=3)),
                ('rh', models.CharField(max_length=2)),
                ('fresh_snow_amount', models.CharField(max_length=3)),
                ('fresh_snow_duration', models.CharField(max_length=4)),
                ('total_fresh_snow_amount', models.CharField(max_length=3)),
                ('standing_snow', models.CharField(max_length=3)),
                ('snow_temperature', models.CharField(max_length=3)),
                ('snow_characteristics_code', models.CharField(max_length=2)),
                ('snow_appearance_code', models.CharField(max_length=1)),
                ('snow_penetration', models.CharField(max_length=2)),
                ('fresh_show_density', models.CharField(max_length=3)),
                ('fresh_show_water_equivalent', models.CharField(max_length=3)),
                ('crystal_type_code', models.CharField(max_length=2)),
                ('storm_board_reading', models.CharField(max_length=3)),
                ('hourly_board_reading_24', models.CharField(max_length=3)),
            ],
        ),
    ]
