# Generated by Django 4.1.3 on 2023-02-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0047_snow_strom_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='snow_profile_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('packet', models.CharField(max_length=255)),
                ('json_packet', models.JSONField()),
                ('message_type', models.IntegerField(default=82)),
                ('state_code', models.IntegerField(verbose_name=range(1, 9))),
                ('station_code', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date', models.CharField(max_length=6)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('slope_aspect', models.CharField(max_length=2)),
                ('slope_angle', models.CharField(max_length=4)),
                ('present_weather', models.CharField(max_length=2)),
                ('cloud_amount', models.CharField(max_length=1)),
                ('cloud_type', models.CharField(max_length=2)),
                ('wind_dir', models.CharField(max_length=4)),
                ('wind_speed', models.CharField(max_length=6)),
                ('dry_bulb_temperature', models.CharField(max_length=3)),
                ('wet_bulb_temperature', models.CharField(max_length=3)),
                ('shear_frame_area', models.CharField(max_length=3)),
                ('weight_of_tube_hammer', models.CharField(max_length=3)),
                ('no_of_strokes', models.CharField(max_length=2)),
                ('height_of_fail', models.CharField(max_length=3)),
                ('total_penetration', models.CharField(max_length=2)),
                ('penetration_n_strokes', models.CharField(max_length=3)),
                ('nfh_p', models.CharField(max_length=3)),
                ('ram_resistance', models.CharField(max_length=3)),
                ('height_above_ground', models.CharField(max_length=3)),
                ('snow_temperature', models.CharField(max_length=3)),
                ('layer_no', models.CharField(max_length=2)),
                ('layer_thickness', models.CharField(max_length=2)),
                ('wetness', models.CharField(max_length=1)),
                ('grain_type', models.CharField(max_length=2)),
                ('grain_size', models.CharField(max_length=1)),
                ('hardness', models.CharField(max_length=1)),
                ('density', models.CharField(max_length=2)),
                ('shear_strength', models.CharField(max_length=3)),
                ('water_equivalent', models.CharField(max_length=3)),
            ],
        ),
    ]
