# Generated by Django 4.1.3 on 2023-02-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0049_avalanche_occurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_forecast_message',
            name='day_2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='weather_forecast_message',
            name='day_3',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='weather_forecast_message',
            name='day_4',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='weather_forecast_message',
            name='day_5',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='weather_forecast_message',
            name='day_6',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
