# Generated by Django 4.1.3 on 2023-03-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wss_handler', '0051_alter_avalanche_message_one_ack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avalanche_message_two',
            name='ack',
        ),
        migrations.RemoveField(
            model_name='avalanche_message_two',
            name='sequence_num',
        ),
    ]
