# Generated by Django 4.1.3 on 2023-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='sensor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='equation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensors',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
