# Generated by Django 4.1.3 on 2023-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_sensors_sensor_name_alter_sensors_equation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(unique=True),
        ),
    ]
