# Generated by Django 4.1.3 on 2023-02-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0004_alter_weather_grids_sect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_grids',
            name='forecast_area',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
