# Generated by Django 4.1.3 on 2023-02-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0006_alter_weather_grids_sect_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather_codes',
            old_name='Legend',
            new_name='legend',
        ),
        migrations.AlterField(
            model_name='weather_grids',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
