# Generated by Django 4.1.3 on 2023-02-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0007_rename_legend_weather_codes_legend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_codes',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='weather_codes',
            name='relation_in_char',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
