# Generated by Django 4.1.3 on 2023-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0008_alter_weather_codes_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_codes',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
