# Generated by Django 4.1.3 on 2023-02-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0009_alter_weather_codes_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_forecast_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
    ]
