# Generated by Django 4.1.3 on 2023-02-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0010_weather_forecast_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='weather_grids',
            name='natsat_grids',
        ),
        migrations.AddField(
            model_name='weather_grids',
            name='natsat_grids',
            field=models.ManyToManyField(to='weather_fore.grids'),
        ),
    ]
