# Generated by Django 4.1.3 on 2023-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0011_grids_remove_weather_grids_natsat_grids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grids',
            name='grid_id',
            field=models.CharField(max_length=2550000),
        ),
    ]
