# Generated by Django 4.1.3 on 2023-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0013_alter_grids_grid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='weather_send_temp_packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.CharField(max_length=6)),
                ('grid_id', models.CharField(max_length=4)),
                ('num_of_day', models.CharField(blank=True, max_length=2, null=True)),
                ('day_1', models.CharField(max_length=2)),
                ('day_2', models.CharField(blank=True, max_length=2, null=True)),
                ('day_3', models.CharField(blank=True, max_length=2, null=True)),
                ('day_4', models.CharField(blank=True, max_length=2, null=True)),
                ('day_5', models.CharField(blank=True, max_length=2, null=True)),
                ('day_6', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
