# Generated by Django 4.1.3 on 2023-02-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0014_weather_send_temp_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_send_temp_packet',
            name='num_of_day',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
