# Generated by Django 4.1.3 on 2023-02-27 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0015_alter_weather_send_temp_packet_num_of_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather_send_temp_packet',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
