# Generated by Django 4.1.3 on 2023-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0016_rename_start_data_weather_send_temp_packet_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_send_temp_packet',
            name='forecast_area',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
