# Generated by Django 4.1.3 on 2023-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0019_weather_area_update_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_area_update_message',
            name='send_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
