# Generated by Django 4.1.3 on 2023-03-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_fore', '0021_weather_code_update_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_code_update_message',
            name='message_type',
            field=models.IntegerField(default=97),
        ),
    ]
